version: '3.0'

services:

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    environment:
      - VIRTUAL_HOST=test
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
    container_name: php
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./html/:/var/www/html/
    networks:
      - backend

  mysql:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    tty: true
    environment:
      - VIRTUAL_HOST=phpmyadmin
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - frontend
      - backend

networks:
  frontend:
    external:
      # здесь нужно указать имя сети, которую создал nginx-proxy (посмотреть можно через docker network ls)
      name: nginx-proxy_proxy
  backend: